name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk zip unzip git python3-dev build-essential libssl-dev libffi-dev libncurses5-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
      - name: Build APK
        run: |
          yes | buildozer android debug || true
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yopic-APK
          path: bin/*.apk
